# @package _global_

defaults:
  - _self_
  - data: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /home/dev/lightning-hydra-template/logs/train/runs/2023-04-26_08-38-16/checkpoints/epoch_009.ckpt
